services:
  nexus3:
    container_name: nexus3
    image: registry.cloud.lab/sonatype/nexus3:3.67.1
    volumes:
      - /nexus-data:/nexus-data
    ports:
      - "0.0.0.0:8081:8081"
      - "0.0.0.0:8082:8082"
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:8084:8084"
      - "0.0.0.0:8085:8085"
      - "0.0.0.0:8088:8088"
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4096M
    restart: always
  nginx:
    container_name: nginx
    image: registry.cloud.lab/nginx:1.26.0
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl/cert.crt:/etc/nginx/ssl/cert.crt
      - ./etc/nginx/ssl/cert.key:/etc/nginx/ssl/cert.key
    deploy:
      resources:
        limits:
          memory: 512M
    network_mode: "host"
    restart: always

networks:
  net:
    driver: bridge
