version: '3.9'

services:
  nexus3:
    container_name: nexus3
    image: registry-docker.cloud.lab/sonatype/nexus3:3.52.0
    volumes:
      - /nexus-data:/nexus-data
    ports:
      - "0.0.0.0:8081:8081"
      - "0.0.0.0:8082:8082"
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:8084:8084"
      - "0.0.0.0:8085:8085"
    deploy:
      resources:
        limits:
          memory: 4096M
    restart: always
  nginx:
    container_name: nginx
    image: registry-docker.cloud.lab/nginx:stable
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl/cert.crt:/etc/nginx/ssl/cert.crt
      - ./etc/nginx/ssl/cert.key:/etc/nginx/ssl/cert.key
    deploy:
      resources:
        limits:
          memory: 512M
    network_mode: "host"
    restart: always
  portainer_agent:
    container_name: portainer_agent
    image: registry-docker.cloud.lab/portainer/agent:2.18.1
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
